# Generated by Django 2.2.6 on 2019-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
