# Generated by Django 2.2.6 on 2019-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0002_imagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
