# Generated by Django 2.2.6 on 2019-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0003_auto_20191025_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
