# Generated by Django 2.2.6 on 2019-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0004_auto_20191025_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
