# Generated by Django 2.2.6 on 2019-12-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0005_imagepost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='tags'
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('post', models.ManyToManyField(to='image_post.ImagePost')),
            ],
        ),
    ]
