# Generated by Django 2.2.6 on 2019-12-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_post', '0006_auto_20191231_0435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
